# Generated by Django 5.1.2 on 2025-06-06 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('genre', 'Genre'), ('explicit', 'Explicit Genre')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='YuriAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mal_id', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='images/anime/')),
                ('trailer', models.URLField(null=True)),
                ('titles', models.JSONField()),
                ('type', models.CharField(choices=[('tv', 'TV'), ('ova', 'OVA'), ('movie', 'Movie'), ('special', 'Special'), ('ona', 'ONA'), ('music', 'Music')], max_length=10, null=True)),
                ('source', models.CharField(max_length=100, null=True)),
                ('episodes', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('finished_airing', 'Finished Airing'), ('currently_airing', 'Currently Airing'), ('not_yet_aired', 'Not Yet Aired')], max_length=50, null=True)),
                ('aired', models.JSONField(null=True)),
                ('duration', models.CharField(max_length=50, null=True)),
                ('rating', models.CharField(choices=[('g', 'G - All Ages'), ('pg', 'PG - Children'), ('pg_13', 'PG-13 - Teens 13 or older'), ('r', 'R - 17+ (violence & profanity)'), ('r+', 'R+ - Mild Nudity'), ('rx', 'Rx - Hentai')], max_length=50, null=True)),
                ('score', models.FloatField(null=True)),
                ('scored_by', models.IntegerField(null=True)),
                ('popularity', models.IntegerField(null=True)),
                ('synopsis', models.CharField(max_length=10000, null=True)),
                ('season', models.CharField(choices=[('winter', 'Winter'), ('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall')], max_length=50, null=True)),
                ('year', models.IntegerField(null=True)),
                ('themes', models.JSONField(null=True)),
                ('genres', models.ManyToManyField(null=True, related_name='animes', to='app.genre')),
                ('producers', models.ManyToManyField(null=True, to='app.producer')),
                ('studios', models.ManyToManyField(null=True, to='app.studio')),
            ],
        ),
    ]
