# Generated by Django 5.1.2 on 2025-06-06 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YuriAnime',
            new_name='Anime',
        ),
    ]
