# Generated by Django 5.1.2 on 2025-06-06 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_theme_alter_anime_producers_alter_anime_studios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='animes', to='app.genre'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='producers',
            field=models.ManyToManyField(blank=True, related_name='animes', to='app.producer'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='studios',
            field=models.ManyToManyField(blank=True, related_name='animes', to='app.studio'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='themes',
            field=models.ManyToManyField(blank=True, related_name='animes', to='app.theme'),
        ),
    ]
