# Generated by Django 5.1.2 on 2025-06-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_genre_mal_id_producer_mal_id_studio_mal_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='rating',
            field=models.CharField(choices=[('G - All Ages', 'G'), ('PG - Children', 'Pg'), ('PG-13 - Teens 13 or older', 'Pg 13'), ('R - 17+ (violence & profanity)', 'R'), ('R+ - Mild Nudity', 'R Plus'), ('Rx - Hentai', 'Rx')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='season',
            field=models.CharField(choices=[('Winter', 'Winter'), ('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='status',
            field=models.CharField(choices=[('Finished Airing', 'Finished'), ('Currently Airing', 'Currently'), ('Not Yet Aired', 'Not Yet')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='type',
            field=models.CharField(choices=[('TV', 'Tv'), ('OVA', 'Ova'), ('Movie', 'Movie'), ('Special', 'Special'), ('ONA', 'Ona'), ('Music', 'Music')], max_length=10, null=True),
        ),
    ]
