# Generated by Django 5.1.2 on 2025-06-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_anime_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='type',
            field=models.CharField(choices=[('TV', 'Tv'), ('OVA', 'Ova'), ('Movie', 'Movie'), ('Special', 'Special'), ('TV Special', 'Tvspecial'), ('ONA', 'Ona'), ('Music', 'Music')], max_length=10, null=True),
        ),
    ]
