# Generated by Django 5.1.2 on 2025-06-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_anime_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='status',
            field=models.CharField(choices=[('Finished Airing', 'Finished'), ('Currently Airing', 'Currently'), ('Not yet aired', 'Not Yet')], max_length=50, null=True),
        ),
    ]
